import {
  AlarmSmoke,
  Apple,
  Bath,
  Bed,
  Bike,
  Book,
  BookOpen,
  Brain,
  Brush,
  CalendarCheck,
  CalendarDays,
  ClipboardList,
  Coffee,
  CookingPot,
  CigaretteOff,
  Droplet,
  Dumbbell,
  EggFried,
  Footprints,
  Heart,
  Laptop,
  Leaf,
  Lightbulb,
  Milk,
  Moon,
  MoonStar,
  Music,
  NotebookPen,
  PenLine,
  PersonStanding,
  Pill,
  Salad,
  Search,
  ShowerHead,
  Soup,
  Sparkles,
  Sprout,
  Sun,
  Sunrise,
  Target,
  Timer,
  Utensils,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/** Free/open-source lucide icons (ISC) — matches app terminal aesthetic. Stored as string keys. */
export const ROUTINE_ICONS = {
  sprout: Sprout,
  target: Target,
  sunrise: Sunrise,
  sun: Sun,
  moon: Moon,
  'moon-star': MoonStar,
  bed: Bed,
  dumbbell: Dumbbell,
  footprints: Footprints,
  bike: Bike,
  'person-standing': PersonStanding,
  droplet: Droplet,
  coffee: Coffee,
  milk: Milk,
  pill: Pill,
  utensils: Utensils,
  soup: Soup,
  salad: Salad,
  'egg-fried': EggFried,
  apple: Apple,
  'cooking-pot': CookingPot,
  'shower-head': ShowerHead,
  bath: Bath,
  brush: Brush,
  sparkles: Sparkles,
  laptop: Laptop,
  book: Book,
  'book-open': BookOpen,
  brain: Brain,
  'notebook-pen': NotebookPen,
  'pen-line': PenLine,
  'cigarette-off': CigaretteOff,
  'alarm-smoke': AlarmSmoke,
  search: Search,
  'clipboard-list': ClipboardList,
  calendar: CalendarDays,
  'calendar-check': CalendarCheck,
  timer: Timer,
  lightbulb: Lightbulb,
  zap: Zap,
  heart: Heart,
  music: Music,
  leaf: Leaf,
} as const satisfies Record<string, LucideIcon>

export type RoutineIconKey = keyof typeof ROUTINE_ICONS

export const ROUTINE_ICON_KEYS = Object.keys(ROUTINE_ICONS) as RoutineIconKey[]

export const DEFAULT_ROUTINE_ICON: RoutineIconKey = 'sprout'

/** legacy emoji → lucide key (migrate old localStorage) */
const EMOJI_MAP: Record<string, RoutineIconKey> = {
  '🎯': 'target',
  '🌅': 'sunrise',
  '☀️': 'sun',
  '🌙': 'moon',
  '😴': 'bed',
  '🛏️': 'bed',
  '💪': 'dumbbell',
  '🏋️': 'dumbbell',
  '🚶': 'footprints',
  '🏃': 'bike',
  '🤸': 'person-standing',
  '🧘': 'person-standing',
  '💧': 'droplet',
  '☕': 'coffee',
  '🍵': 'coffee',
  '💊': 'pill',
  '🍽️': 'utensils',
  '🥞': 'egg-fried',
  '🍜': 'soup',
  '🍲': 'soup',
  '🥗': 'salad',
  '🚿': 'shower-head',
  '🪥': 'brush',
  '🧴': 'sparkles',
  '💻': 'laptop',
  '📚': 'book',
  '📖': 'book-open',
  '🧠': 'brain',
  '📓': 'notebook-pen',
  '📝': 'pen-line',
  '🙏': 'heart',
  '🚬': 'cigarette-off',
  '🔍': 'search',
  '📋': 'clipboard-list',
  '📅': 'calendar',
  '📆': 'calendar-check',
  '✅': 'calendar-check',
}

/** routine name keyword → icon key */
const KEYWORD_MAP: Record<string, RoutineIconKey> = {
  pagi: 'sunrise',
  pagi2: 'sunrise',
  morning: 'sunrise',
  sunrise: 'sunrise',
  sore: 'sun',
  siang: 'sun',
  afternoon: 'sun',
  evening: 'moon',
  night: 'moon',
  malam: 'moon',
  tidur: 'bed',
  sleep: 'bed',
  istirahat: 'bed',
  rest: 'bed',
  olahraga: 'dumbbell',
  gym: 'dumbbell',
  workout: 'dumbbell',
  walk: 'footprints',
  jalan: 'footprints',
  running: 'bike',
  lari: 'bike',
  yoga: 'person-standing',
  stretch: 'person-standing',
  streching: 'person-standing',
  air: 'droplet',
  water: 'droplet',
  minum: 'droplet',
  coffee: 'coffee',
  kopi: 'coffee',
  tea: 'coffee',
  teh: 'coffee',
  susu: 'milk',
  milk: 'milk',
  suplemen: 'pill',
  suplement: 'pill',
  vitamin: 'pill',
  obat: 'pill',
  makan: 'utensils',
  breakfast: 'egg-fried',
  makan_pagi: 'egg-fried',
  lunch: 'soup',
  makan_siang: 'soup',
  dinner: 'cooking-pot',
  makan_malam: 'cooking-pot',
  healthy: 'salad',
  salad: 'salad',
  buah: 'apple',
  fruit: 'apple',
  mandi: 'shower-head',
  shower: 'shower-head',
  gigi: 'brush',
  brush: 'brush',
  skincare: 'sparkles',
  care: 'sparkles',
  kerja: 'laptop',
  work: 'laptop',
  coding: 'laptop',
  programming: 'laptop',
  belajar: 'book',
  study: 'book',
  baca: 'book-open',
  read: 'book-open',
  focus: 'target',
  deep: 'brain',
  deep_work: 'brain',
  journal: 'notebook-pen',
  diary: 'notebook-pen',
  log: 'pen-line',
  note: 'pen-line',
  tulis: 'pen-line',
  meditasi: 'person-standing',
  meditate: 'person-standing',
  gratitude: 'heart',
  ucapan: 'heart',
  rokok: 'cigarette-off',
  smoke: 'cigarette-off',
  review: 'search',
  plan: 'clipboard-list',
  rencana: 'clipboard-list',
  weekly: 'calendar',
  monthly: 'calendar-check',
  cek: 'calendar-check',
  check: 'calendar-check',
  habit: 'target',
  routine: 'sprout',
  rootine: 'sprout',
  timer: 'timer',
  pomodoro: 'timer',
  music: 'music',
  musik: 'music',
}

export function normalizeRoutineIcon(raw: string | undefined, name = ''): RoutineIconKey {
  if (raw && raw in ROUTINE_ICONS) return raw as RoutineIconKey
  if (raw && raw in EMOJI_MAP) return EMOJI_MAP[raw]
  const key = name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_|_$/g, '')
  if (key && key in KEYWORD_MAP) return KEYWORD_MAP[key]
  return DEFAULT_ROUTINE_ICON
}

export function RoutineIcon({
  icon,
  className,
}: {
  icon: string
  className?: string
}) {
  const Cmp = ROUTINE_ICONS[normalizeRoutineIcon(icon)] ?? ROUTINE_ICONS[DEFAULT_ROUTINE_ICON]
  return <Cmp className={className ?? 'w-3.5 h-3.5 inline-block shrink-0'} aria-hidden />
}
